---
title: "R Notebook"
output: html_notebook
---

```{r Load Libraries, message=FALSE, warning=FALSE}
# Load libraries
library(tidyverse)
library(janitor)
library(lme4)
library(broom)
library(broom.mixed)
library(sjPlot)
library(assertr)
library(skimr)
```


OK! After messy code in 12_, 13_, and 14_ (should clean it up, eek), we have CRQA results all over. Cool. Let's load 'em all and smoosh up all the input data and output variables in one neat data frame. 

```{r Loading & Tidying Data, message=FALSE, warning=FALSE}

# This are the data frames (with lists, etc.) used for finding the optimal
# radius for each person's eye gaze, against both the right hand and the left
# hand. First, we took all data associated with each story x direction x hand,
# and found the optimal embeddim and delay parameters for each via the
# optimizeParam() function. Then we ran those optimal parameters in CRQAs with a
# radius range of 5-60 ("test radius") to get associated rr_values. The target
# rr_value was 5, and the test radius that produced the target rr_value was then
# used for the final CRQA.
crqa_inputdata_r <- readRDS("crqa_rhand.RDS") %>%
  add_column(hand = "right") %>%
  rename(hand_y = rhand_y,
         hand_len = rhand_len,
         radius = test_radius)
  
crqa_inputdata_l <- readRDS("crqa_lhand.RDS") %>%
  add_column(hand = "left") %>%
  rename(hand_y = lhand_y,
         hand_len = lhand_len,
         radius = test_radius)

input_data <- bind_rows(crqa_inputdata_r,
                        crqa_inputdata_l)

rm('crqa_inputdata_r')
rm('crqa_inputdata_l')


# These are the CRQA results for each participant x story x direction x hand,
# using the test radius found above.
crqa_results_r <- read_csv("crqa_results_rhand.csv") %>%
  add_column(hand = "right") %>%
  rename_at(vars(rhand_rr:rhand_tt), ~ str_remove(.x, "rhand_")) %>%
  rename(radius = optimized_r)

crqa_results_l <- read_csv("crqa_results_lhand.csv") %>%
  add_column(hand = "left") %>%
  rename_at(vars(lhand_rr:lhand_tt), ~ str_remove(.x, "lhand_")) %>%
  rename(radius = optimized_r)

results <- bind_rows(crqa_results_r,
                     crqa_results_l)

rm('crqa_results_r')
rm('crqa_results_l')

# Now combine everything in one neat data frame
final <- results %>%
  left_join(input_data, by = c("name",
                               "maingroup",
                               "story",
                               "direction",
                               "embeddim",
                               "delay",
                               "radius",
                               "hand")) %>%
  verify(rr == rr_values) %>%
  mutate_at(vars(name, maingroup, story, direction, hand), as.factor) %>%
  select(-rr_values)

rm('results')
rm('input_data')

skim(final)
```



